bot:
  name: &botname Lemon Tools
  author: &author Windows95
  sudos: ["330539533546422272", "666731058649366556"]
  description: >-
    Lemon Tools is multipurpose bot, with many features not provided by other bots, 
    such as QR Code creation, giveaways and much more! Lemon Tools aims to be the Swiss Knife
    of Discord Bots!
  perms: 274878286912

style:
  # Colour *must* be spelt the proper way
  # a.k.a. the non-US way
  colour:
    primary: "#FEF250"
    secondary: "Secondary colour hex code."