bot:
  name: &botname Lemon Tools
  author: &author Compositr
  sudos: ["330539533546422272"]
  description: >-
    Lemon Tools is multipurpose bot, with many features not provided by other bots, 
    such as QR Code creation, giveaways and much more! Lemon Tools aims to be the Swiss Knife
    of Discord Bots!
  perms: 274878286912

style:
  colour:
    primary: "#FEF250"
    secondary: "Secondary colour hex code."

  status:
    type: WATCHING
    message: /help

modules: 
  ReminderManager:
    checkInterval: 60_000
    doInitialSweep: true
  MonitoringManager:
    enabled: true
